### ISSUE TITLE
Linux版服務器, 執行shutdown.sh/startup.sh後, 服務器設定與資料被清除, 但Windows客戶端資料仍然存在, 產生不同部現象

### ISSUE THREAD

**Issue by TravisLo** [isuncloud/linux_server#5]
Server: Linux mgt
Windows Client: setup20150215

step:
客戶端將含有相片檔案的folder拉入我的云盤
Linux服務器執行./shutdown.sh & ./startup.sh, 關閉服務器再啟動的動作.
此時服務器端的資料被清除(使用"My Cloud"查看)
查看Ｗindows client, 可發現資料仍在
客戶端若執行"開始同步", 則資料會被清除

expected:
1. 此時接入碼已被清除, client應無法執行同步工作
2. 若無接入碼也可同步, 則系統應該要能自動同步

未同步時:
![screen_0317_04](https://cloud.githubusercontent.com/assets/11288965/6683622/b9596f8e-ccc3-11e4-80c7-a48fa4f06008.png)

執行"我的同步後":
![screen_0317_06](https://cloud.githubusercontent.com/assets/11288965/6683642/dbfddde0-ccc3-11e4-9861-109c51a0aa48.png)

**Comment by lukechang0815** [comment]
linux 0520 verified
