### ISSUE TITLE
Linux版服務器, 陽光雲管理系統系統設定, 無法更改存儲位置

### ISSUE THREAD

**Issue by TravisLo** [isuncloud/linux_server#6]
Server: Linux mgt

step:
由Ｗeb(chrome) 進入http://192.168.26.4:9000/admin/settings頁面
更改存儲位置的路徑, c:/isuncloud --> c:/isuncloud1, 結果顯示存儲位置不正確

expected:
可以更改存儲位置

提交前
![screen_0318_01](https://cloud.githubusercontent.com/assets/11288965/6705252/e582aee8-cd8d-11e4-8414-34c17b5850f6.png)
提教後
![screen_0318_02](https://cloud.githubusercontent.com/assets/11288965/6705255/f1aa6d5a-cd8d-11e4-808c-b13a740c6e8a.png)

**Comment by lukechang0815** [comment]
0520 verified
